ELMo: {
  name: 'pt'
}

ASSIN: {
  path: './datasets/ASSIN/',
  files: {
    ptbr: {
      'train': 'assin-ptbr-train-hartmann.json'
      'test': 'asssin-ptbr-test-gold-hartmann.json'
    }
  }
}

NILC: {
  dir: './embeddings/USP/',  
  sources: [
    http://143.107.183.175:22980/download.php?file=embeddings/word2vec/cbow_s50.zip,
    http://143.107.183.175:22980/download.php?file=embeddings/word2vec/cbow_s100.zip,
    http://143.107.183.175:22980/download.php?file=embeddings/word2vec/cbow_s300.zip,
    http://143.107.183.175:22980/download.php?file=embeddings/word2vec/cbow_s600.zip,
    http://143.107.183.175:22980/download.php?file=embeddings/word2vec/cbow_s1000.zip,
    http://143.107.183.175:22980/download.php?file=embeddings/word2vec/skip_s50.zip,
    http://143.107.183.175:22980/download.php?file=embeddings/word2vec/skip_s100.zip,
    http://143.107.183.175:22980/download.php?file=embeddings/word2vec/skip_s300.zip,
    http://143.107.183.175:22980/download.php?file=embeddings/word2vec/skip_s600.zip,
    http://143.107.183.175:22980/download.php?file=embeddings/word2vec/skip_s1000.zip,
    http://143.107.183.175:22980/download.php?file=embeddings/fasttext/cbow_s50.zip,
    http://143.107.183.175:22980/download.php?file=embeddings/fasttext/cbow_s100.zip,
    http://143.107.183.175:22980/download.php?file=embeddings/fasttext/cbow_s300.zip,
    http://143.107.183.175:22980/download.php?file=embeddings/fasttext/cbow_s600.zip,
    http://143.107.183.175:22980/download.php?file=embeddings/fasttext/cbow_s1000.zip,
    http://143.107.183.175:22980/download.php?file=embeddings/fasttext/skip_s50.zip,
    http://143.107.183.175:22980/download.php?file=embeddings/fasttext/skip_s100.zip,
    http://143.107.183.175:22980/download.php?file=embeddings/fasttext/skip_s300.zip,
    http://143.107.183.175:22980/download.php?file=embeddings/fasttext/skip_s600.zip,
    http://143.107.183.175:22980/download.php?file=embeddings/fasttext/skip_s1000.zip,
    http://143.107.183.175:22980/download.php?file=embeddings/wang2vec/cbow_s50.zip,
    http://143.107.183.175:22980/download.php?file=embeddings/wang2vec/cbow_s100.zip,
    http://143.107.183.175:22980/download.php?file=embeddings/wang2vec/cbow_s300.zip,
    http://143.107.183.175:22980/download.php?file=embeddings/wang2vec/cbow_s600.zip,
    http://143.107.183.175:22980/download.php?file=embeddings/wang2vec/cbow_s1000.zip,
    http://143.107.183.175:22980/download.php?file=embeddings/wang2vec/skip_s50.zip,
    http://143.107.183.175:22980/download.php?file=embeddings/wang2vec/skip_s100.zip,
    http://143.107.183.175:22980/download.php?file=embeddings/wang2vec/skip_s300.zip,
    http://143.107.183.175:22980/download.php?file=embeddings/wang2vec/skip_s600.zip,
    http://143.107.183.175:22980/download.php?file=embeddings/wang2vec/skip_s1000.zip,
    http://143.107.183.175:22980/download.php?file=embeddings/glove/glove_s50.zip,
    http://143.107.183.175:22980/download.php?file=embeddings/glove/glove_s100.zip,
    http://143.107.183.175:22980/download.php?file=embeddings/glove/glove_s300.zip,
    http://143.107.183.175:22980/download.php?file=embeddings/glove/glove_s600.zip,
    http://143.107.183.175:22980/download.php?file=embeddings/glove/glove_s1000.zip
  ]
}