ELMo: {
  name: 'pt'
}

ASSIN: {
  path: './datasets/ASSIN/',
  entailment: {
    -1: 'NONE',
    0: 'NONE',
    1: 'ENTAILMENT',
    2: 'PARAPHRASE'
  },
  files: {
    ptbr: {
      'train': 'assin-ptbr-train-hartmann.json',
      'test': 'assin-ptbr-test-gold-hartmann.json'
    },
    pteu: { 
      'train': 'assin-ptpt-train-hartmann.json',
      'test': 'assin-ptpt-test-gold-hartmann.json'
    }
  }
}

SICK: {
  path: './datasets/SICK/',
  files: {
    en: {
      'train': 'SICK_train.json',
      'test': 'SICK_test.json'
    }
  }
}

unzip: {
  'cores': 8
}

logs: {
  path: './logs/'
}

results: {
  path: './results/'
}

gensim: {
  'memory_percent_limit': 50.0,
  'wait_interval': 1,
  'cores': 1
}

reddit: {
  pushshift: 'http://files.pushshift.io/reddit/comments/',
  path: './reddit/'
}

NILC: {
  dir: '../embeddings/NILC/', 
  analogies: './analogies/',
  sources: [
    "http://143.107.183.175:22980/download.php?file=embeddings/word2vec/cbow_s50.zip",
    "http://143.107.183.175:22980/download.php?file=embeddings/word2vec/cbow_s100.zip",
    "http://143.107.183.175:22980/download.php?file=embeddings/word2vec/cbow_s300.zip",
    "http://143.107.183.175:22980/download.php?file=embeddings/word2vec/cbow_s600.zip",
    "http://143.107.183.175:22980/download.php?file=embeddings/word2vec/cbow_s1000.zip",
    "http://143.107.183.175:22980/download.php?file=embeddings/word2vec/skip_s50.zip",
    "http://143.107.183.175:22980/download.php?file=embeddings/word2vec/skip_s100.zip",
    "http://143.107.183.175:22980/download.php?file=embeddings/word2vec/skip_s300.zip",
    "http://143.107.183.175:22980/download.php?file=embeddings/word2vec/skip_s600.zip",
    "http://143.107.183.175:22980/download.php?file=embeddings/word2vec/skip_s1000.zip",
    "http://143.107.183.175:22980/download.php?file=embeddings/fasttext/cbow_s50.zip",
    "http://143.107.183.175:22980/download.php?file=embeddings/fasttext/cbow_s100.zip",
    "http://143.107.183.175:22980/download.php?file=embeddings/fasttext/cbow_s300.zip",
    "http://143.107.183.175:22980/download.php?file=embeddings/fasttext/cbow_s600.zip",
    "http://143.107.183.175:22980/download.php?file=embeddings/fasttext/cbow_s1000.zip",
    "http://143.107.183.175:22980/download.php?file=embeddings/fasttext/skip_s50.zip",
    "http://143.107.183.175:22980/download.php?file=embeddings/fasttext/skip_s100.zip",
    "http://143.107.183.175:22980/download.php?file=embeddings/fasttext/skip_s300.zip",
    "http://143.107.183.175:22980/download.php?file=embeddings/fasttext/skip_s600.zip",
    "http://143.107.183.175:22980/download.php?file=embeddings/fasttext/skip_s1000.zip",
    "http://143.107.183.175:22980/download.php?file=embeddings/wang2vec/cbow_s50.zip",
    "http://143.107.183.175:22980/download.php?file=embeddings/wang2vec/cbow_s100.zip",
    "http://143.107.183.175:22980/download.php?file=embeddings/wang2vec/cbow_s300.zip",
    "http://143.107.183.175:22980/download.php?file=embeddings/wang2vec/cbow_s600.zip",
    "http://143.107.183.175:22980/download.php?file=embeddings/wang2vec/cbow_s1000.zip",
    "http://143.107.183.175:22980/download.php?file=embeddings/wang2vec/skip_s50.zip",
    "http://143.107.183.175:22980/download.php?file=embeddings/wang2vec/skip_s100.zip",
    "http://143.107.183.175:22980/download.php?file=embeddings/wang2vec/skip_s300.zip",
    "http://143.107.183.175:22980/download.php?file=embeddings/wang2vec/skip_s600.zip",
    "http://143.107.183.175:22980/download.php?file=embeddings/wang2vec/skip_s1000.zip",
    "http://143.107.183.175:22980/download.php?file=embeddings/glove/glove_s50.zip",
    "http://143.107.183.175:22980/download.php?file=embeddings/glove/glove_s100.zip",
    "http://143.107.183.175:22980/download.php?file=embeddings/glove/glove_s300.zip",
    "http://143.107.183.175:22980/download.php?file=embeddings/glove/glove_s600.zip",
    "http://143.107.183.175:22980/download.php?file=embeddings/glove/glove_s1000.zip"
  ]
}
